---
# Apply configuration files
#
#
- template:
    src: ../templates/99_config.j2
    dest: /etc/netplan/99_config.yaml

- template:
    src: ../templates/99-openstack.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf

- template:
    src: ../templates/cinder.j2
    dest: /etc/cinder/cinder.conf

- template:
    src: ../templates/dhcp_agent.j2
    dest: /etc/neutron/dhcp_agent.ini

- template:
    src: ../templates/etcd.j2
    dest: /etc/default/etcd

- template:
    src: ../templates/glance-api.j2
    dest: /etc/glance/glance-api.conf

- template:
    src: ../templates/glance-registry.j2
    dest: /etc/glance/glance-registry.conf

- template:
    src: ../templates/hosts.j2
    dest: /etc/hosts

- template:
    src: ../templates/keystone.j2
    dest: /etc/keystone/keystone.conf

- template:
    src: ../templates/l3_agent.j2
    dest: /etc/neutron/l3_agent.ini

- template:
    src: ../templates/linuxbridge_agent.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

- template:
    src: ../templates/local_settings.j2
    dest: /etc/openstack-dashboard/local_settings.py

- template:
    src: ../templates/lvm.j2
    dest: /etc/lvm/lvm.conf

- template:
    src: ../templates/memcached.j2
    dest: /etc/memcached.conf

- template:
    src: ../templates/metadata_agent.j2
    dest: /etc/neutron/metadata_agent.ini

- template:
    src: ../templates/ml2_conf.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini

- template:
    src: ../templates/neutron.j2
    dest: /etc/neutron/neutron.conf

- template:
    src: ../templates/nova.j2
    dest: /etc/nova/nova.conf

- template:
    src: ../templates/openstack-dashboard.j2
    dest: /etc/apache2/conf-available/openstack-dashboard.conf


