---
# Install the apt packages
##
- shell: add-apt-repository cloud-archive:rocky

- apt:
    update_cache: yes
   #force: yes

- apt:
    name: '{{ item }}'
    state: latest
    #force: yes
  with_items: '{{ packages }}'
