---
# tasks file for aio

- name: Install Packages
  include_tasks: install_packages.yml

- name: Apply Config Files
  include_tasks: apply_configs.yml

- name: Create RabbitMQ User
  include_tasks: setup_rabbit.yml

- name: Setup MySQL
  include_tasks: setup_mysql.yml

- name: Setup Keystone
  include_tasks: setup_keystone.yml

- name: Setup Glance
  include_tasks: setup_glance.yml

- name: Enable etcd Service
  include_tasks: enable_etcd.yml

- name: Setup Controller and Compute
  include_tasks: setup_controller_compute.yml

- name: Setup Neutron
  include_tasks: setup_neutron.yml

- name: Setup Horizon
  include_tasks: setup_horizon.yml

- name: Setup Cinder
  include_tasks: setup_cinder.yml
