---

- apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items:
    - mariadb-server
    - mariadb-client

- service:
    name: mysql
    state: started
    enabled: yes

#- shell: mysql --user="root" --password="S3cur3" --database="mysql" --execute="ALTER USER root@localhost IDENTIFIED VIA mysql_native_password;"

- apt:
    name: python-mysqldb
    state: latest

- mysql_db:
    name: '{{item}}'
    state: present
    collation: utf8_general_ci
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - keystone
    - glance
    - nova_api
    - nova
    - nova_cell0
    - placement
    - neutron
    - cinder

- mysql_user:
    name: '{{item}}'
    priv: '*.*:ALL'
    state: present
    password: S3cur3
    host: '%'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - keystone
    - glance
    - nova_api
    - nova
    - nova_cell0
    - placement
    - neutron
    - cinder

