---
# Initialize keystone
- command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- shell: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- shell: keystone-manage bootstrap --bootstrap-password S3cur3 --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

- lineinfile:
    path: /etc/apache2/apache2.conf
    state: present
    line: 'ServerName controller'

- service:
    name: apache2
    state: restarted

- shell: openstack project create --domain default --description "Service Project" service
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: S3cur3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  ignore_errors: yes
  #debug: msg='This might fail if the openstack resource was already created'

- shell: openstack project create --domain default --description "Demo Project" myproject
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: S3cur3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  ignore_errors: yes
  #debug: msg='This might fail if the openstack resource was already created'

- shell: openstack user create --domain default --password S3cur3 myuser
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: S3cur3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  ignore_errors: yes
  #debug: msg='This might fail if the openstack resource was already created'

- shell: openstack role create myrole
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: S3cur3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  ignore_errors: yes
  #debug: msg='This might fail if the openstack resource was already created'

- shell: openstack role add --project myproject --user myuser myrole
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: S3cur3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  ignore_errors: yes
  #debug: msg='This might fail if the openstack resource was already created'

