---
# Initialize Glance

- shell: openstack user create --domain default --password S3cur3 glance

- shell: openstack role add --project service --user glance admin

- shell: openstack service create --name glance --description "OpenStack Image" image

- shell: openstack endpoint create --region RegionOne image public http://controller:9292

- shell: openstack endpoint create --region RegionOne image internal http://controller:9292

- shell: openstack endpoint create --region RegionOne image admin http://controller:9292

- shell: su -s /bin/sh -c "glance-manage db_sync" glance

- service:
    name: glance-registry
    state: restarted

- service:
    Name: glance-api
    state: restarted
