---
# Initialize Neutron

- shell: openstack user create --domain default --password S3cur3 neutron # The prompt will prompt for the password input
  ignore_errors: yes

- shell: openstack role add --project service --user neutron admin
  ignore_errors: yes

- shell: openstack service create --name neutron --description "OpenStack Networking" network
  ignore_errors: yes

- shell: openstack endpoint create --region RegionOne network public http://controller:9696
  ignore_errors: yes

- shell: openstack endpoint create --region RegionOne network internal http://controller:9696
  ignore_errors: yes

- shell: openstack endpoint create --region RegionOne network admin http://controller:9696
  ignore_errors: yes

- service:
    name: nova-compute
    state: restarted

- service:
    name: neutron-linuxbridge-agent
    state: restarted

- shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- service:
    name: nova-api
    state: restarted

- service:
    name: neutron-server 
    state: restarted

- service:
    name: neutron-linuxbridge-agent 
    state: restarted

- service:
    name: neutron-dhcp-agent 
    state: restarted

- service:
    name: neutron-metadata-agent 
    state: restarted

- service:
    name: neutron-l3-agent 
    state: restarted

